package com.clubloyalty.server.domain;

import javax.persistence.*;
import java.time.Instant;

@Entity
@Table(name = "notifications")
public class Notification {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(optional = false)
    private Member member;

    @Column(nullable = false)
    private String title;

    @Column(nullable = false, length = 1000)
    private String message;

    @Column(nullable = false)
    private String type;

    @Column(nullable = false, updatable = false)
    private Instant createdAt = Instant.now();

    private Instant readAt;

    private boolean autoGenerated = true;

    public Notification() {
    }

    public Notification(Member member, String title, String message, String type, boolean autoGenerated) {
        this.member = member;
        this.title = title;
        this.message = message;
        this.type = type;
        this.autoGenerated = autoGenerated;
    }

    public Long getId() {
        return id;
    }

    public Member getMember() {
        return member;
    }

    public String getTitle() {
        return title;
    }

    public String getMessage() {
        return message;
    }

    public String getType() {
        return type;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public Instant getReadAt() {
        return readAt;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public void markRead() {
        this.readAt = Instant.now();
    }
}
